#!/usr/bin/env -S fish --no-config
set containr (set char $argv[1]; echo $char | python3 -c "for i in range(0xC0,0x2B0): print(chr(i))" | grep -x "[[=$char=]]")
if test -n "$argv[4]" -a -n "$argv[5]"
    set modeuse $argv[4]
    if test $modeuse = "rga"
        set variants[1] $argv[2]
        set variants[1] "-e \""$variants[1]"\""
        set i 2
        for c in $containr
            set variants[$i] $argv[2]
            set variants[$i] (echo $variants[$i] | sed s/./$c/$argv[3])
            set variants[$i] "-e \""$variants[$i]"\""
            set i (math $i+1)
        end
        set rgastr (echo -n $argv[5])
        for inni in (seq $i)
            set rgastr $rgastr (echo -n $variants[$inni])
        end
        set rgastr $rgastr (echo " ./*")
        eval $rgastr
    end
else if test -n "$argv[1]" -a -n "$argv[2]" -a -n "$argv[3]"
    set variants[1] $argv[2]
    set i 2
    for wc in $containr
        set variants[$i] $argv[2]
        set variants[$i] (echo $variants[$i] | sed s/./$wc/$argv[3])
        set i (math $i+1)
    end
    echo $variants
else
    echo "Error: you need at least three arguments—character to query, sample text, and a positive index to replace."
end

